silvershop/silvershop-core

code/checkout/components/MembershipCheckoutComponent.php

Given a single-page checkout and given the membership component comes after the address book components, the addresses don't get assigned to the member correctly. Supercedes #276.

Fixes a checkout bug related to Member addresses

---

code/product/Product.php
example_config.yml

The problem we face is that our inventory system measures lengths in metres and SS Shop currently uses centimetres.  This pull request proposes an additional decimal place for the length measurement to enable accuracy down to millimetres, plus the ability to customise the CMS presentation through mysite/config.yml.

Customise weight/lengths measurement

---

code/cart/ShoppingCart.php
code/product/variations/VariationForm.php
composer.json

This PR doesn't add full ajax support but it adds extension hooks to make that happen. In the mean time, so that these features can be used safely in modules, I've separated the actual features into a couple modules. I felt the ajax module itself could be useful outside of the shop module so I think we should probably leave it separate. If you want to merge the shop-ajax module into shop core to keep from having two sets of pull requests in the future, I'm totally fine with that.
- https://github.com/markguinn/silverstripe-ajax
- https://github.com/markguinn/silverstripe-shop-ajax
This is a resubmission of #275 because that PR failed Travis/Scrutinizer (due to timeouts). Since that issue has been resolved I'm resubmitting this.

Added hooks for ajax integration

---

code/cart/MatchObjectFilter.php
tests/cart/MatchObjectFilterTest.php
tests/products/CustomProductTest.php

There is a discrepancy between how `has_one` and `db` fields are handled when required but no matching data is supplied. The former results in a filter of `("FieldNameID" = 0 OR "FieldNameID" = NULL)` while the latter produces `"FieldName" = null` (invalid).
The PR changes the behaviour so that `db` fields result in a filter of `"FieldName" IS NULL`.
Also updated existing `CustomProductTest` and created `MatchObjectFilterTest`.

Handle missing required values consistently in MatchObjectFilter.

---

code/model/Order.php

Without an implementation of canView, only administrators could view
order details.
Fixes #322

Add canView check to Order.

---

code/checkout/OrderEmail.php
code/checkout/OrderEmailNotifier.php
code/checkout/OrderProcessor.php
docs/en/02_Customisation/Emails.md
docs/en/index.md
templates/email/Order_AdminNotificationEmail.ss
templates/email/Order_ConfirmationEmail.ss

I've added in a 'confirmation email' , which gets sent when an order is placed, but not yet paid for. Receipt is sent after payment.
Also added a AdminNotification email. The email notification to the admin sometimes needs to be different.
Refactored OrderProcessor email stuff into its own class.
Updated docs

Email refactor + improvement

---

code/checkout/components/AddressBookCheckoutComponent.php
javascript/CheckoutPage.js

… outside of $(document).ready
This prevents fields disappearing after page has fully loaded, which could be seconds later if other javascript is loading/running (especially external scripts). I think we can assume the relevant DOM will be loaded since javascript is added to the bottom of the page.
I've also reorganised code to be  narrower, thus readable.

Moved the CheckoutPage extistingValues toggle code

---

docs/en/01_Getting_Set_Up/01_Installation.md
docs/en/01_Getting_Set_Up/03_Troubleshooting.md
docs/en/01_Getting_Set_Up/04_Shipping.md
docs/en/01_Getting_Set_Up/05_Tax.md
docs/en/01_Getting_Set_Up/Tasks.md
docs/en/01_Getting_Set_Up/index.md
docs/en/02_Customisation/01_Recipes/Custom_Checkout.md
docs/en/02_Customisation/01_Recipes/Customising_Fields.md
docs/en/02_Customisation/01_Recipes/Multi_Step_Checkout.md
docs/en/02_Customisation/01_Recipes/Multiple_Images_Product.md
docs/en/02_Customisation/Contributing.md
docs/en/02_Customisation/Submodules.md
docs/en/02_Customisation/Testing.md
docs/en/02_Customisation/index.md
docs/en/03_How_It_Works/Architecture.md
docs/en/03_How_It_Works/Core_Changes.md
docs/en/03_How_It_Works/Development.md
docs/en/03_How_It_Works/Member.md
docs/en/03_How_It_Works/Release_Process.md
docs/en/index.md
docs_user/en/AddingEditingProducts.md
docs_user/en/ProductVariations.md
docs_user/en/index.md

Includes:
- some additional links in the Developer doc's index.md that were missing;
- shifted Development.md to 03_How_It_Works folder;
- added .md to file names to make links work on Github;
- updated silverstripe/PHPUnit links

Updated docs for broken links

---

code/product/Product.php

Unfortunately cms SiteTree doesn't allow overriding labels that it has defined, so we need to kind of hack it in.

Change Product Title label to "Title" (Rather than "Page Name")

---

code/account/AccountPage.php
code/checkout/CheckoutForm.php
code/model/Address.php
tests/account/AccountPageTest.php
tests/checkout/CheckoutComponentTest.php
tests/checkout/CheckoutFormTest.php
tests/checkout/OrderProcessorTest.php
tests/fixtures/shop.yml
tests/fixtures/singlecountry.yml

The readonly field of Country_readonly (when operating in a single country) is not passed onto the saveaddress function.  Null is saved to the database.  Add a new textfield to the save address function.  
Is this the best solution?

Update AccountPage.php for Country saved as null

---

code/checkout/CheckoutPage.php
code/checkout/steps/CheckoutStep_Summary.php
code/model/Order.php

+Minor bugfix and tidy
Allow summary checkout component config to be updated in extensions./
Fix to prevent payment field manipulation in the case that such fields don't exist

Added CheckoutStep_Summary component config extension hook.

---

code/checkout/components/AddressBookCheckoutComponent.php

Adds jquery as a requirement before the CheckoutPage.js requirement.
I'm not entirely sure this is the best approach, but I thought I'd at least bring it to your attention.
I'd personally rather include the js via a template, but I guess it depends how closely the js is tied to the php code.

Include jquery javascript requirement in AddressBookCheckoutComponent

---

code/product/variations/ProductVariationsExtension.php

Changed the range value to be SellingPrice not Price on Product Variations.
If variations were extended via updateSellingPrice() then this function would of just used the standard Price. This will prevent that.

Changed range value to be SellingPrice not Price

---

code/account/ShopAccountForm.php
code/account/ShopMemberFactory.php
code/checkout/components/AddressBookCheckoutComponent.php
code/checkout/components/MembershipCheckoutComponent.php

If field-labels are translated, use them in error-messages. If there's no translation, keep the field-name.

Use localized field-names in error- and validation-messages.

---

code/product/Product.php

Added a new function to retrieve category options without ancestors
included in the list.
The issue was caused by the main category not yet being selected

Fixed issue #380

---

code/model/Address.php

I'm using this for setting Germany as the default country like this:
public function updateCountryField($field) {
$field->setHasEmptyDefault(false);
$field->setValue('DE');
}

Allow hooking into `getCountryField`

---

tests/ShopTest.php
tests/cms/ProductBulkLoaderTest.php

Don't rely on silverstripe path, but rather use paths that are calculated relative to the file. Allows execution of tests when folders are symlinked.

Fix for #405

---

code/model/OrderStatusLog.php

The OrderProcessor class has a depreciation notice on it's sendStatusChange function.  Send a status change via the notifier property on the Order class instead.  Thanks.

Updated OrderStatusLog.php

---

code/ShopTools.php
code/cart/CartForm.php
code/cart/ShoppingCart.php
code/checkout/OrderProcessor.php
code/model/Order.php
code/product/AddProductForm.php
code/product/variations/VariationForm.php

Added locale db-field to order.
Added helper tools to get/set current locale.
Ensure locale is properly saved while an order is in `Cart` state.
Install the saved locale during order processing.
Install order-locale for ajax requests to ensure ajax response is rendered with the proper locale.

Add Locale information to Order. Fixes #403

---

code/checkout/CheckoutPage.php
code/checkout/steps/CheckoutStep_Address.php
code/checkout/steps/CheckoutStep_AddressBook.php
code/checkout/steps/CheckoutStep_ContactDetails.php
code/checkout/steps/CheckoutStep_Membership.php
code/checkout/steps/CheckoutStep_PaymentMethod.php
code/checkout/steps/CheckoutStep_Summary.php

CheckoutComponentConfig behaves differently when instancing with `create`. Thus switch back to creation with `new`.

Fixing issue introduced with previous PR.

---

code/account/ShopAccountForm.php

Since the `updateShopAccountForm` hook could add form-fields, the form should be populated afterwards.

Population of the form with data should take place after the form fields are completely built.

---

code/checkout/OrderProcessor.php

For subsequent payments on the same order, change the `transactionId` by adding an incrementing number to the order-id.
Fixes #438

Make transaction-id unique.

---

code/exceptions/ShopBuyableException.php
code/product/Product.php
code/product/variations/ProductVariation.php

Fixing issue #443, where `$quantity` won't be passed to the `canPurchase` method in extensions.
Deprecate `ShopBuyableException`.

Fix `canPurchase` method.

---

code/checkout/PaymentForm.php

Does anyone see a problem with this? It's helpful for the Braintree integration I'm working on because it means the payment gateway gets to see fields in the input that aren't prefixed with `OnsitePaymentCheckoutComponent_` - in this case `payment_method_nonce`.
The worry would be this gives a bit more surface for an attacker to say inject things like the amount (although that specific one is covered). The PurchaseService does explicitly set some things and I don't see any obvious attack vectors.

Pass more data through to the payment processor if needed

---

css/order.css
templates/Includes/OrderReceiptStyle.ss
templates/email/Order_AdminNotificationEmail.ss
templates/email/Order_ConfirmationEmail.ss
templates/email/Order_ReceiptEmail.ss
templates/email/Order_StatusEmail.ss

Uncommented the global resets in OrderReceiptStyle.ss and provided some base styles as recommended by seanpowell/Email-Boilerplate.   Also added a table#container wrapper to provide left/right padding in emails.  Thanks.

Updated OrderReceiptStyle.ss for Email CSS Resets

---

code/account/OrderActionsForm.php
code/checkout/Checkout.php
code/checkout/CheckoutFieldFactory.php
code/checkout/OrderProcessor.php
code/checkout/PaymentForm.php
code/checkout/components/CheckoutComponentConfig.php
code/checkout/components/OnsitePaymentCheckoutComponent.php
code/checkout/components/PaymentCheckoutComponent.php
code/checkout/steps/CheckoutStep_PaymentMethod.php
composer.json
tests/model/ShopPaymentTest.php

See https://github.com/burnbright/silverstripe-omnipay/pull/104.
Also fix deprecated `Member::get_unique_identifier_field()` usage.

No longer use deprecated methods (snake_case) of the omnipay module

---

code/checkout/OrderProcessor.php

Set the success/failure URLs directly on the payment and not the service.
Establish compatibility with: https://github.com/silverstripe/silverstripe-omnipay/pull/125

Set continue URLs on payment and not service.

---

_config/extensions.yml
code/model/ShopPaymentService.php

New feature in the silverstripe-omnipay 2.0 module.

Ensure that OrderID is also being set on partial payments

---

code/product/AddProductForm.php

The numeric field in `AddProductForm` was using the translation as field name.

Fixed order of constructor arguments.

---

code/model/Order.php
code/model/OrderStatusLog.php
tests/model/OrderTest.php

Don't delete Payments.
Cleaned up `OrderStatusLog`.
Added Unit-Test for order delete functionality.
Added missing assertions to can-functions test.
Fixes #484

Ensure related DataObjects of an order are deleted.

---

code/checkout/OrderEmailNotifier.php
code/checkout/OrderProcessor.php
code/model/Order.php
tests/model/OrderTest.php

Set order paid date and send recipe when the order-status changes to `Paid`. This is needed to properly mark an order as Paid in cases where Payments don't reach the total amount (eg. an authorized payment that was only partially captured)
Modified OrderProcessor to just set order status to `Paid` if order is fully paid.
Added Unit-Tests.
Removed redundant write in `OrderEmailNotifier`.
Fix for #496

Update order upon setting Status to Paid.

---

code/product/variations/VariationForm.php

Page load is exponentially slowed on products with multiple attribute types due to the hidden input field that's generated by Variation Form. This fix has reduced the script execution time up to this point by over 50% on my local tests and reduces further as the number of product variations increases.

Improve the way variation options are generated

---

templates/Includes/Cart.ss

the structure for setting properties on table columns is `<colgroup><col class="a"><col class="b"></colgroup> ... `. Column Groups without cols make little sense.

colgroup should be col

---

code/ShopBuyableException.php
code/cart/CartForm.php
code/product/AddProductForm.php
code/product/variations/ProductVariationsExtension.php
code/product/variations/VariationForm.php

Opening this up for discussion for the core-team (@markguinn, @wilr, @anselmdk), or any interested party. 
We have deprecated `ShopBuyableException` and removed it with 2.0. Some of the reasoning can be found in this issue: #443
The gist of it:
- Throwing an Exception from `canPurchase` seemed like a non-intuitive architecture, since the method already tells us whether or not a product can be purchased.
- The only reason the Exception was used there, was to pass a message to the outside.
Since `2.0` was our only chance to clean up API (before 3.0), I'd rather keep the exception removed and look for a short-term and long-term solution to the problem.
Proposed short-term fix:
- Remove exception throwing from the [silvershop-stock](https://github.com/silvershop/silvershop-stock) module, so …

Revert commits that re-added the ShopBuyableException.

---

code/cart/CartForm.php
code/cart/ShoppingCart.php
code/product/variations/ProductVariationsExtension.php
tests/cart/ShoppingCartTest.php

This allows extensions to interrupt updates to the cart.
Update CartForm to collect/display bad messages from shopping-cart.

Wrap all order extension hooks in try/catch blocks.

---

code/tasks/ShopEmailPreviewTask.php

So that they work with SilverStripe installations located in a subfolder.
Pinging @anselmdk for review.

Update preview links for ShopEmailPreviewTask

---

templates/Layout/Product.ss
templates/Layout/ProductCategory.ss

To keep the main content on top for mobile phones.
Changing the order via css is supported by frameworks like Foundation and Bootstrap. For mobile it needs to be on top though.

moving the sidebar to the end of the page

---

code/cart/CartForm.php
code/cart/MatchObjectFilter.php
code/cart/ShoppingCart.php
code/product/variations/VariationForm.php

For this to work, the following had to be changed:
- CartForm must remove the order item by ID, not by lookup via Buyable
- ShoppingCart must supply methods to directly remove or update an OrderItem
- enable the “saveabledata” parameters for the VariationForm as well (not just AddProductForm)

Improve/enable custom properties on OrderItems.

---

code/checkout/steps/CheckoutStep_Summary.php

The `updateConfirmationForm`form extension appears twice in the CheckoutStep_Summary class.  Remove from ConfirmationForm function and leave in the summary function, as this this closer to the final return statement.

Updated CheckoutStep_Summary.php

---

code/model/Order.php

Added hooks for `canCancel`, `canPay`, `canDelete`, `canView`, `canEdit` and `canCreate`

Allow extensions to hook into the permission methods of `Order`.

---

composer.json

I'm pretty sure dev-master shouldn't be an alias for 1.2 and should be for 2.2
Also, you may want to consider making it an alias for 2.x instead of 2.2.x - but I'll leave that up to you.

Update composer alias for master branch

---

src/Cart/ShoppingCart.php
src/Checkout/Component/Membership.php
src/Checkout/OrderProcessor.php
src/Extension/MemberExtension.php
src/ShopTools.php
tests/php/Extension/MemberExtensionTest.php

Fix issue with a PHP error showing up after logout (session was manipulated, but already cleared).

Fix issue where newly created member wasn't logged in after completing an order.

---

docs/en/01_Getting_Set_Up/02_Upgrading.md
example_config.yml
lang/da.yml
lang/de.yml
lang/en.yml
lang/fr.yml
lang/nb.yml
lang/nl.yml
lang/nn.yml
src/Admin/ProductBulkLoader.php
src/Extension/ProductVariationsExtension.php
src/Page/Product.php

The `CostPrice` field is never used throughout the codebase (also checked all repositories within `silvershop`).
It only creates confusion for content-authors.
If a module uses another price-field, such as `CostPrice`, the module should add it.

Remove the CostPrice field from Product.

---

src/Checkout/CheckoutComponentConfig.php
src/Checkout/Component/CheckoutComponent.php
src/Checkout/Component/CheckoutComponentNamespaced.php
src/Checkout/Component/OnsitePayment.php
src/Forms/PaymentForm.php
src/Page/CheckoutPageController.php

No longer depend on a hardcoded checkout-component type. Use a property instead.

Improve how onsite-payments are routed.

---

.upgrade.yml
ChangeLog.md
_config/config.yml
_config/model.yml
src/Checkout/OrderEmailNotifier.php

Change the OrderEmailNotifier accordingly.
Change debug output of emails, so that the ShopEmailPreviewTask is usable.

Remove the "ShopEmail" injector setting.

---

code/cart/ShoppingCart.php

This keeps it in line with the `afterSetQuantity`, allowing for more flexibility. Note however it is added as a fourth parameter, which differs from `afterSetQuantity` but it keeps the integrity of the public API;

added $item as a parameter for beforeSetQuantity

---

tests/php/Checkout/Component/CheckoutComponentTest.php
tests/php/Extension/SteppedCheckoutExtensionTest.php
tests/php/Fixtures/singlecountry.yml
tests/php/Forms/CheckoutFormTest.php
tests/php/Forms/OrderActionsFormTest.php
tests/php/Page/AccountPageTest.php

AllowedCountries are now JSON encoded.
Fix changes that were made to the omnipay `Dummy` gateway.

Fix issues with unit-tests.

---

.travis.yml
code/product/Product.php
tests/account/OrderActionsFormTest.php
tests/checkout/SteppedCheckoutTest.php

(fields were previously positioned _before_ the `Content` field)
Update/fix unit-tests.

Restore previous field positions 

---

example_config.yml
src/Extension/ShopConfigExtension.php
src/ORM/Filters/MultiFieldPartialMatchFilter.php
src/Reports/ShopPeriodReport.php

With the default config settings I've had to make these changes to get the admin interface not breaking with SS41.
The following were broken:
* Viewing list of orders
* Viewing a single order
* Shop reports where a date range was included.  I've added a config override here, but the default behavior should be the same as it was before.

Fixes admin interface ss41

---

example_config.yml

Commented out `global_allow_purchase: false` so that the cart can be added to immediately following use of example_config.yml in a new site

Updated example_config.yml

---

src/Checkout/Step/Membership.php

Without explicitely using "Layout" in the template name it gets wrapped
in global Page.ss which is the desired behaviour

CheckoutPage_membership should be treated as Layout

---

src/Checkout/OrderProcessor.php

Fixes an error, where no emails / receipts are sent, when an order is paid (via payment provider). We have local mail set up , no SMTP. The problem is, that Swift standard transport is deprecated and throws a E_USER_DEPRECATED error which is now ignored.

Exclude deprecations from custom error handler

---

src/ORM/FieldType/ShopCountry.php

Use IntlLocales to get the localized country name. This saves having to keep a file with translated country names.

Use IntlLocales to get the localized country name

---

src/Model/Variation/AttributeType.php

In the frontend dropdown the Label field should be used instead of the Name field.
This is mentioned in the source:
```
private static $db = [
'Name' => 'Varchar', //for back-end use
'Label' => 'Varchar' //for front-end use
];
```

Use Label as title for frontend dropdown field

---

src/Model/Order.php

Changed the order so that if Logged in user is sent to account page instead of checkout page.

Order Link function should point to account if logged in

---

src/Cart/OrderTotalCalculator.php

Currently if modifier is already defined in a third party config, defining the modifier in the main app cause errors. This pull request will make sure that only unique set of modifiers from the config is used.

Add unique modifiers from the config

---

src/Checkout/OrderProcessor.php
src/Model/Order.php
src/Model/Variation/Variation.php

During a recent upgrade project, we reviewed an old fork that we were on of silverstripe-shop (the precursor to silvershop).
During this, I found the following changes that were missing from silvershop-core, there are four distinct things that we've added / resolved (each commit is a single fix/change that we've made).
The four changes are:
- Fix OrderProcessor not setting the paid date when an order has nothing outstanding
- Show any OrderModifiers added to the order when viewing order details in CMS
- Allow order total calculation to always include any applied discounts/coupons
- Provide a Link method for product variations that links to the product page
I'm happy to raise these as individual pull requests if you'd prefer, but thought that all four are relatively benign so it made sense …

Misc fixes made during project

---

ChangeLog.md
src/Checkout/OrderEmailNotifier.php
src/Model/Order.php
src/Model/OrderStatusLog.php

Should be backwards-compatible. Includes an upgrade task that correctly sets the flag for old records
- Add new boolean flag VisibleToCustomer to OrderStatusLog
- Add requireDefaultRecords to migrate and upsert the new VisibleToCustomer flag to existing records
- Add description for existing SentToCustomer field (after discussion on it's purpose with wilr) and VisibleToCustomer
- Set new flag appropriately in existing logic
- Add note to changelog for an upcoming (unreleased) version

FEAT: Add new VisibleToCustomer flag to OrderStatusLog

---

ChangeLog.md
src/Model/OrderStatusLog.php
tests/php/Model/OrderStatusLogTest.php

As per description. Added the following the the changelog which describes the feature:
Add new `order_is_required` config flag to `OrderStatusLog`, set to true by default (for backwards-compatibility). Set it to `false` to allow `OrderStatusLog` objects to be created that are not linked to any particular `Order` object.
This change is backwards-compatible to 3.0.0.

FEAT: Allow OrderStatusLog objects to *not* be forcibly linked to an order

---

src/Model/Order.php

This allows for much faster DB queries when searching for 'Cart' orders, something silvershop now does I think when viewing any product page.
On a database that has ~200k randomly generated fake orders, average query times are:
| Description | Time | Notes |
|-------|-----|-----|
| Before any indexes | **1.3s** | MySQL using filesort, 200k rows |
| After adding 'Status' index only | **1.1ms** | Still using filesort, but on only 20 'Cart' rows |
| After adding both indexes | **0.8ms** | No filesort anymore |

FEAT: Add table index for Status and the Status/Placed/Created tuple

---

src/Extension/ProductImageExtension.php

- per Silverstripe 4.0 Filesystem changelog: https://docs.silverstripe.org/en/4/changelogs/4.0.0/#overview-filesystem, Image::SetSize() should be replaced with Image::Pad()
- fixes incorrect image size displayed on shop

FIX: Replace Image::Fit() with Image::Pad()

---

src/Checkout/Component/Membership.php

With the stepped checkout process, a new member can be created at the beginning of the checkout process.  If the customer does not complete the checkout process, we end up with a member in SilverStripe without a group.  Therefore, add the Customer Group to a new member immediately after creation.  Thank you.

Updated SilverShop\Checkout\Component\Member.php

---

src/Checkout/OrderEmailNotifier.php

By passing the HTMLText object the text renders properly in the email

Get the dbObject instance of the PurchaseComplete message

---

src/Checkout/OrderProcessor.php

Don't throw exceptions for suppressed errors in the custom error handler in OrderProcessor when placing an order.
The error use case we encountered is when sending an order receipt e-mail that uses some image manipulation functions (for example FitMax) in the e-mail template. If the original image includes incorrect exif data, then intervention image will still try to orient the image, using exif_read_data which in turn triggers an error. Even though the exif_read_data call suppresses errors via the @ operator, the custom error handler in OrderProcessor is still triggered and throws an Exception, which causes intervention image to believe the image cannot be read and the image manipulation is skipped.
The solution is to simply check the error reporting level and error severity in the …

Don't throw exceptions for suppressed errors

---

docs/en/02_Customisation/OrderStatusEmailNotifications.md
src/Model/Order.php

This will allow for a nieche scenario where a user may desire to change their email used for order notifications without affecting the email used for logging in, payments etc.

Allow overriding of latest email for order

---

src/Forms/PaymentForm.php

Under certain circumstances an order with different modifiers (e.g. discount, free-shipping with min. price) can calculate a new total-price before it is submitted to the payment-gateway. The changed total-price should be saved before the submit to avoid miscalculations afterwards. Problems occur when place_before_payment is switched off.

Recalculated Order should be saved

---

src/Admin/ProductBulkLoader.php
src/Cart/OrderTotalCalculator.php
src/Cart/ShoppingCartController.php
src/Checkout/CheckoutComponentConfig.php
src/Checkout/OrderProcessor.php
src/Forms/OrderActionsForm.php
src/Forms/VariationForm.php
src/Model/Order.php
src/Model/OrderStatusLog.php
src/Model/Variation/Variation.php
src/Page/Product.php
src/Reports/ProductReport.php
src/Tasks/PopulateShopTask.php
tests/php/Model/OrderStatusLogTest.php

PR following a review of the Scrutinizer reports.  Thanks.

Minor updates as highlighted by Scrutinizer

---

client/dist/javascript/CheckoutPage.nojquery.js
src/Checkout/Component/AddressBook.php

- Added js file with vanilla javascript to avoid using jquery. 
- Updated AddressBook Component to load CheckoutPage.nojquery.js file instead jquery if no jquery file is defined.

Added nojquery js for addressbook display logic

---

composer.json

I've started the work to upgrade this module to Silverstripe 5 and have managed it with very few changes required. 
It's not mergeable as-is unless you add my forks to the repositories key to your parent project (composer seems to ignore the upstream ones).  The pull requests need to be accepted, so I can update this pull request to use a stable tag, or a specific commit until it is marked stable
```
"repositories": {
"silvershop/core": {
"type": "vcs",
"url": "git@github.com:elliot-sawyer/silvershop-core.git"
},
"silvershop/silverstripe-listsorter": {
"type": "vcs",
"url": "git@github.com:elliot-sawyer/silverstripe-listsorter.git"
},
"silvershop/silverstripe-sqlquerylist": {
"type": "vcs",
"url": "git@github.com:elliot-sawyer/silverstripe-sqlquerylist.git"
}
},
```
The only coding change …

Silverstripe 5 support

---

.github/workflows/ci.yml

CI was failing, cause it's trying to install silverstripe-omnipay:dev-master, which doesn't exist any more. It was renamed to dev-main

CI: omnipay doesn't have a master branch any more

---

client/dist/javascript/CheckoutPage.nojquery.js
src/Checkout/Component/AddressBook.php

I provided a new variable which now holds the translated AddressType for types Billing and Shipping. The default EN value remains as fallback as there were customizations made, like renaming the type in an extension

Fix $this->addresstype only contains EN value

---

src/Checkout/OrderEmailNotifier.php

Changed the debug function to be compatible with symfony/mailer.  Thanks.

Update OrderEmailNotifier.php for SS5

---

client/dist/css/shopcms.css
lang/de.yml
lang/en.yml
lang/hr.yml
lang/nb.yml
lang/nl.yml
lang/nn.yml
src/Model/Modifiers/OrderModifier.php
src/Model/Order.php
src/Reports/AbandonedCartReport.php
src/Reports/CustomerReport.php
src/Reports/ProductReport.php
src/Reports/ShopSalesReport.php
src/Reports/TaxReport.php

somehow related to #779 some more formatting for different prices in the backend.
For formatting payments see https://github.com/silverstripe/silverstripe-omnipay/issues/244
@wilr and/or @forsdahl please have a look at this PR and merge if possible. I disabled OrderModifier's Amount() method which should be fine IMHO but could possibly break some stuff.

Fix currency formatting

---

src/Page/ProductCategory.php

Don't allow archiving of a category if it has products assigned to it.

---

docs/en/02_Customisation/Emails.md
example_config.yml
src/Checkout/OrderProcessor.php
src/Model/Order.php
tests/php/Checkout/OrderEmailNotifierTest.php

For when a site is only using the Manual payment method (confirmation email has already been sent to the customer) and a second email upon payment is not needed.  Thanks.

Provide an option to disable the emailing of receipts

---

_config/config.yml
src/Cart/ShoppingCartController.php
src/Extension/MemberExtension.php
src/Extension/ProductImageExtension.php

Some variables are declared in config.yml.  Shift them into the classes so that they can be found :).  Thanks.

Shift private static variables from yaml file to classes

---

src/Cart/ShoppingCartController.php
tests/php/Cart/ShoppingCartControllerTest.php

The response object should be a `HTTPResponse`, and only be set in the case of an error. 
If increasing the number of items is successful, the response should be `null`. 
If the response is given (!= `null`), the `redirect` method will try to redirect to that response. In this case, because the response is set to a string, we get a white screen of death.
This issue was introduced by https://github.com/silvershop/silvershop-core/commit/3427d6327b3d158322a6cf32df395602e09031f1#diff-adc2d15f712ffc2573c65cfa5e8217efeaf1bd035ed5efed08be0658d0e4d878R210.

fix response when increasing number of item in cart is successful
