silvershop/silvershop-core

- code/account/AccountPage.php
Provide the user with a success message when adding a new address on the Accounts Page
> Create Address Form Success Message

- code/product/AddProductForm.php
Split fields, actions and validator creation into protected methods that can be overriden in sub-classes.
Relates to #312
> Refactor AddProductForm for greater extensibility.

- code/checkout/steps/CheckoutStep_Membership.php
> Fix 404 when logging in with invalid credentials

- .editorconfig
- docs/en/02_Customisation/Contributing.md
For contributors who's editors/IDE support it, this will save us from having to push back on some style issues in PR's (primarily spaces => tabs). Check out http://editorconfig.org/ for more information.
I'll leave this open for a week or so for anyone to push back and/or add rules to the file as you see fit.
> Created simple .editorconfig

- code/cart/CartEditField.php
- code/cart/CartForm.php
- code/cart/CartPage.php
I've refactored things even further, especially note the introduction of CartEditField.
I've done away with the static method all together.
@wilr
> CartForm refactor to allow greater customisation

- code/account/AccountPage.php
Provide an extension point in the CreateAddressForm in AccountPage.php.  Thanks.
> Update AccountPage.php for a form extension point

- README.md
To reflect the fact I'm not maintaining so much anymore. Could add in your name @markguinn , but people could also just check the contributors list.
> Removed maintainers section from README

- code/product/ProductCategory.php
Provides an extension point so you can apply extra filters . e.g. brands, cost range etc.
> Add extension point for ProductsShowable

- code/model/Address.php
- tests/model/AddressTest.php
Added UnitTest to ensure functionality.
> Fix issue #369. Use `getRequiredFields` in the Address' validate method.

- code/checkout/steps/SteppedCheckout.php
- tests/checkout/SteppedCheckoutTest.php
Added function to check if steps exist
> Added function to check if checkout step exists

- .travis.yml
- code/account/AccountPage.php
- code/account/ShopMemberFactory.php
- code/cart/MatchObjectFilter.php
- code/model/Order.php
- code/model/OrderAttribute.php
- composer.json
- tests/cart/MatchObjectFilterTest.php
- tests/model/OrderTest.php
- tests/travis/upload_coverage.sh
The module actually works fine with 3.2 but tests don't pass. This branch is trying to fix that and also trying to get Scrutinizer reconnected. (Please no-one merge this because I'll want to squash all these random commits first)
> Changes for 3.2 compatibility

- lang/de.yml
- lang/en.yml
The collected english text (via Textcollector) and the german translation provided by @anselmdk merged in.
> Merge collected english and german text. Validated resulting YML.

- code/product/AddProductForm.php
To be used with PR on silverstripe-shop-ajax
> Allow AddProductForm to be submitted via AJAX

- code/cart/CartEditField.php
- code/product/AddProductForm.php
Make sure users cannot enter negative numbers or characters into the quantity fields.
> Make add to cart form and cart form have to enter a positive numbers

- lang/en.yml
- templates/Includes/Cart.ss
- templates/Includes/ProductGroupPagination.ss
Some minor improvements to wrap up #368.
> Minor cleanup on translations.

- code/ShopTools.php
- code/cart/CartForm.php
- code/cart/ShoppingCart.php
- code/checkout/OrderProcessor.php
- code/model/Order.php
- code/product/AddProductForm.php
- code/product/variations/VariationForm.php
Cherry picking the changes applied with #411 to the `develop` branch.
> Applied changes from #411 to develop branch.

- templates/order/Order.ss
tbody needs to be open.
Thanks
> Update Order.ss for incorrectly closed tbody element

- code/account/ShopAccountForm.php
@markguinn Try this. I gave up on the other pr as it wouldn't let me merge the commits.
> Update account form extend

- docs/en/01_Getting_Set_Up/01_Installation.md
Provided summarised instructions for installing Silverstripe Shop.  Also included a note about installing a demo in localhost (personally found this really useful).
> Updated 01_Installation.md

- css/order.css
- templates/order/Order.ss
- templates/order/Order_Address.ss
- templates/order/Order_Content.ss
- templates/order/Order_Content_ItemLine.ss
- templates/order/Order_Content_SubTotals.ss
- templates/order/Order_ItemLine.ss
- templates/order/Order_Payments.ss
Checked html in the Order Templates and revised where necessary.  Adjusted css where appropriate.  Removed div, paragraphs and headings as the order templates are also used in emails.
> Revised Order Templates and associated CSS

- example_config.yml
Changed the After so changes in this file will actually overwrite any config settings in the shop/config.yml
> Make example config overwrite shop/config.yml

- _config/countries.yml
- _config/extensions.yml
- lang/it.yml
- lang/nb.yml
Updated two config files.  Array listing needed under 'After:'
Updated two language files for unescaped quotes
Thanks
> Updated config and language files for incorrect yaml

- code/checkout/components/AddressCheckoutComponent.php
This is the same as before, except I didn't really like the overriding of the core toMap functionality so removed that.
This meant I had to do the same thing but within the setData function so its now secluded to one place.
The additional bit that has changed is the getData section, it checks to see if an address is set first, if it is then it doesn't bother overriding it with the members default address (which is what it was doing). This is what resulted in blank fields keeping the default address.
> Fixed issue with address duplication due to blank or readonly fields

- example_config.yml
Changed the folder name from 'shop' to 'silvershop'
> Updated example_config.yml for new folder name

- templates/Layout/CheckoutPage_membership.ss
Translate "Log in" in Checkout-Membership by using the framework translation Security.LOGIN
> Translate "Log in" in checkout-page.

- code/product/variations/ProductVariation.php
Minor code cleanup (removed trailing commas in arrays).
> Fix translations that were added to ProductVariation (remove `sprintf`).

- README.md
- code/account/AccountPage.php
- css/account.css
- example_config.yml
- templates/Layout/AccountPage.ss
- templates/Layout/AccountPage_addressbook.ss
- templates/Layout/AccountPage_editprofile.ss
- templates/Layout/AccountPage_order.ss
This allows you to create an interface like this:
https://www.dropbox.com/s/3ff0dlymiopdwps/Screenshot%202016-03-16%2016.02.21.png?dl=0
https://www.dropbox.com/s/3pbjzl5p339hn92/Screenshot%202016-03-16%2016.15.15.png?dl=0
I think that's better than the dropdowns you got by default and this is something we've done on all the sites we've built anyway. Any objections to just adding this as the default UI?
(apparently this also includes a few commits from master that hadn't been pulled into 2.0 yet)
> Improvements to the addressbook UI

- code/product/Product.php
- code/product/variations/ProductVariation.php
- lang/en.yml
Only substitute fields that actually have placeholders in Product and ProductVariation, otherwise PHP will raise a notice.
> Add newly added translation-keys to en.yml.

- code/account/OrderManipulation.php
- code/cart/ShoppingCart.php
> Don't archive the order when viewing.

- code/modifiers/shipping/WeightShippingModifier.php
> Improve weight-shipping-modifier to use config API.

- templates/Includes/OrderReceiptStyle.ss
Tested with both SmtpMailer and EmogrifiedSmtpMailer classes of Silverstripe Email Helpers module.  Thanks.
> Added default order styling back to OrderReceiptStyle.ss for emails

- code/checkout/CheckoutFieldFactory.php
- lang/de.yml
- lang/en.yml
Also fixing small error in german translation (via Transifex)
> Fixing issue in locale files (missing closing curly-bracket)

- code/product/variations/VariationForm.php
Is there is an attribute type with no options then it doesnt return a dropdown. and that breaks the Product with with a 500 error
> Fixed a null pointer issue

- ROADMAP.md
@markguinn / @bummzack this is just an idea. Feel free to merge or amend.
> Starting out on roadmap document

- code/checkout/OrderProcessor.php
- composer.json
Ensure order is recalculated before placing the order or before completing a payment.
> Enforce order recalculation before marking as Paid.

- code/cart/ShoppingCart.php
- example_config.yml
- tests/cart/ShoppingCartControllerTest.php
Added unit-tests and updated example_config.yml.
> Added config setting to disable security-tokens for shopping-cart links.

- templates/order/Order_Payments.ss
Removed the "Note", as this doesn't exist on "Payment" and is therefore superfluous.
> Use translation keys that exist in the omnipay module.

- code/cart/ShoppingCart.php
- tests/cart/ShoppingCartTest.php
Left everything else untouched so there will be no backwards breaks.
> Make ShoppingCart use config and Injector

- _config/config.yml
> Updated config.yml for file path to shopcms.css

- composer.json
Removing more confusion about who is really maintaining this module now :)
> Changed the module author in composer.json

- LICENSE
> Removed copyright

- code/cart/CartPage.php
- code/cart/ViewableCart.php
Actually use the user-setting intead of just defaulting to the topmost product-category.
Fixes #488
> Allow users to select any page type as the shop continue-page.

- .travis.yml
- code/ShopTools.php
- code/cart/OrderTotalCalculator.php
- code/cart/ShoppingCart.php
- code/checkout/OrderProcessor.php
- composer.json
- tests/checkout/OrderProcessorTest.php
- tests/modifiers/OrderModifierTest.php
See issue #198.
Added unit-tests.
> Wrap order-calculations and order placement logic in DB transactions.

- example_config.yml
Changing or adding status to Order's Status Enum field.
> change order status

- code/account/OrderActionsForm.php
- javascript/OrderActionsForm.js
- tests/account/OrderActionsFormTest.php
Added/updated unit-tests.
Fixes #480
> Allow onsite payments on the OrderActionsForm.

- code/product/ProductCategory.php
- lang/de.yml
- lang/en.yml
- lang/nn.yml
Updated en.yml and pulled current translations from transifex.
> Detect sort_options as translatable entities.

- code/product/ProductImage.php
Was scaling the image width with the height setting
> Correct ProductImage to be scaled by Height

- docs/en/01_Getting_Set_Up/02_Upgrading.md
Added a few notes to the Upgrading instructions following upgrading a site to v2.  Thanks.
> Updated 02_Upgrading.md

- example_config.yml
Added an example of overriding Product's $db array with an adjusted data type.  Thank you.
> Updated example_config.yml

- example_config.yml
Added log_status settings example for order status email notifications
> Updated example_config.yml for log_status settings

- code/cms/OrdersAdmin.php
- code/model/OrderStatusLog.php
Provides visibility of the Order Status Logs in a tab on the orders folder.  Thank you.
> Visibility of Order Status Logs within the CMS 

- templates/Includes/Address.ss
Added Company field to Address.ss
> Updated Address.ss for Company field

- code/cart/ShoppingCart.php
Pass quantity to findOrMakeItem() so it can be passed to Buyable::canPurchase()
> Pass quantity to findOrMakeItem()

- code/model/Order.php
- code/model/OrderStatusLog.php
- tests/model/OrderStatusLogTest.php
Ensure status-log email gets sent only once.
Added unit-tests.
> Only create an OrderStatusLog entry when the status has changed.

- code/checkout/OrderEmailNotifier.php
- code/tasks/ShopEmailPreviewTask.php
Helper task for styling emails, see discussion [here](https://gitter.im/silvershop/silvershop-core?at=57ed671f34a8d5681ccb5cdb).
> introducing task ShopEmailPreviewTask

- docs/en/01_Getting_Set_Up/03_Troubleshooting.md
- docs/en/01_Getting_Set_Up/04_Shipping.md
- docs/en/01_Getting_Set_Up/index.md
- docs/en/02_Customisation/Contributing.md
- docs/en/02_Customisation/Testing.md
- docs/en/02_Customisation/index.md
- docs/en/03_How_It_Works/Development.md
- docs/en/03_How_It_Works/Release_Process.md
- docs/en/index.md
Updated links in docs.  Thanks.
> Updated Links in Docs

- CONTRIBUTING.md
& adding "becoming a maintainer"
> Updating links/wording

- code/checkout/OrderProcessor.php
- tests/checkout/OrderProcessorTest.php
Updated unit-test to check order status and ensure receipt was sent.
> Fix issue where order receipt wasn't sent.

- code/model/Buyable.php
I assumed the parameter in the function is correct, it was annoying me that the documentation was different from the function
> Correcting the PHPDoc

- code/cart/ShoppingCart.php
- code/checkout/components/CheckoutComponent.php
Hello all,
I found some inconsistencies in the PHPDocs of this file and wanted to fix them
> Fixing PHPDoc

- code/checkout/OrderEmailNotifier.php
- code/checkout/OrderProcessor.php
- docs/en/02_Customisation/Emails.md
Looking to supply a solution for #569, also fixed a small bit of documentation
> Added a config hook to use a custom notifier

- code/modifiers/tax/FlatTaxModifier.php
Setting the Type in the populateDefaults method was not being picked in the value/totals calculation
> Setting the Type in constructor

- code/product/variations/ProductVariation.php
Fix variation title so it can be extended every time if needed
> Variation title fix

- code/modifiers/shipping/SimpleShippingModifier.php
removed old code from SimpleShippingModifier. It now simply looks at orders shipping address country to determine the shipping cost
> removed old code from SimpleShippingModifier.

- templates/Includes/Price.ss
- templates/Includes/ProductGroupItem.ss
- templates/Layout/Product.ss
> fix price in templates

- code/modifiers/tax/GlobalTaxModifier.php
Also remove the untranslated "for $country"…
> Fix GlobalTaxModifier

- docs/en/01_Getting_Set_Up/Bulk_Loading.md
Added documentation for adding the AdditionalCategories to the csv product import
> Additional Categories

- code/product/AddProductForm.php
- code/product/variations/VariationForm.php
> Fix message encoding issue with `VariationForm`.

- code/cms/dashboard/DashboardRecentOrdersChart.php
> Placed added to group by

- code/cart/CartEditField.php
> Fix for Issue CartEditField using Product

- .travis.yml
- code/checkout/CheckoutPage.php
Fix issue with unset failover object.
Improve travis config.
> Fix travis issues.

- lang/de.yml
- lang/en.yml
- src/Admin/OrdersAdmin.php
- src/Model/Order.php
- src/Page/Product.php
- tests/php/Model/OrderTest.php
> Ensure field-labels are also properly localized.

- src/Checkout/OrderProcessor.php
- tests/php/Checkout/OrderEmailNotifierTest.php
Minor improvement in unit-test that resets any existing config in OrderEmailNotifierTest
> Fix OrderProcessor using the wrong config.

- src/Extension/ProductVariationsExtension.php
So that variation attribute types can be added to a product.
> FIX: Re-add listbox that was removed.

- composer.json
- src/Page/Product.php
This should be integrated via an addon.
> Remove Opengraph integration.

- docs/en/01_Getting_Set_Up/03_Troubleshooting.md
- docs/en/01_Getting_Set_Up/Tasks.md
- docs/en/02_Customisation/01_Recipes/Default_Admin.md
- docs/en/02_Customisation/01_Recipes/Multi_Language.md
- docs/en/03_How_It_Works/Core_Changes.md
- docs/en/03_How_It_Works/Order_Modifiers.md
- docs/en/03_How_It_Works/Product_Variations.md
- example_config.yml
See https://github.com/silvershop/silvershop-core/issues/623
See https://github.com/silvershop/silvershop-core/pull/647
Todo:
> WIP: Update docs to reflect latest changes with SS4

- src/Extension/ProductVariationsExtension.php
- src/Forms/VariationForm.php
- src/Page/Product.php
- src/Page/ProductController.php
Make sure a VariationForm is being used for products with variations (instead of `AddProductForm`).
No longer use a public property that is being modified on the controller. Use a getter with extension hook instead.
> Fix issue in VariationForm.

- docs/en/02_Customisation/01_Recipes/Default_Admin.md
Needs to be after cms' defaultadmin to work
> Fix defaultadmin config docs

- code/cart/ShoppingCart.php
updated visibility of findOrMakeItem from private to protected, in order to allow for overriding the function in subclasses
> updated visibility of findOrMakeItem

- src/Page/Product.php
Fix the results returned by `getCategoryOptionsNoParent`.
Fixes #659
> Add the additional product categories listbox field.

- docs/en/02_Customisation/Emails.md
Namespace fixes in one of the docs
> FIX: Namespacing in documentation was out of date

- src/Checkout/Step/ContactDetails.php
With `skip_if_logged_in` = `true` , it should be redirected to the next step if validation is passed.
> Redirect to the next step if validation is passed

- docs/en/01_Getting_Set_Up/01_InstallationConfiguration.md
Updated the documentation for a smooth setup of a new site
> Updated 01_InstallationConfiguration.md

- docs/en/01_Getting_Set_Up/Bulk_Loading.md
> Updated Bulk_Loading.md

- src/Checkout/Step/Membership.php
- src/Page/CheckoutPageController.php
> fix resolving of index template for stepped checkout - 2nd attempt

- src/Model/OrderItem.php
Added extend point to make it possible to perform additional unique data checks on the orderitem.
> Hook to update uniquedata

- src/Checkout/OrderProcessor.php
Refer to issue 705 - https://github.com/silvershop/silvershop-core/issues/705
> OrderProcessor should not recalculate totals

- src/Model/Modifiers/OrderModifier.php
- src/Model/OrderAttribute.php
- update $searchable_fields
- include get prefix to methods used in configs
> FIX: fix bug preventing the view of each order record in CMS

- src/Model/Variation/OrderItem.php
This function was missing. The version of the ProductVariation should be stored on placement of order.
> Store version of ProductVariation in order

- src/Extension/ShopConfigExtension.php
> ShopConfig should own DefaultProductImage

- docs/en/02_Customisation/01_Recipes/Multi_Step_Checkout.md
Added correct path to the `CheckoutStepShippingMethod` class.  Thanks.
> Updated Multi_Step_Checkout.md

- src/Cart/OrderTotalCalculator.php
use injector instead of `new $class()`
> OrderModifiers cannot use dependency injection

- src/Model/Address.php
> Added Company to front end fields of the Address class

- src/Model/Modifiers/OrderModifier.php
fixed null being passed in PHP 8.1
> PHP8.1 type error

- src/Checkout/Component/AddressBook.php
Update AddressBook translation string by adding the addresstype -  for SS4 version.
> Update AddressBook.php SS4

- docs/en/02_Customisation/Emails.md
- src/Checkout/OrderEmailNotifier.php
- src/Tasks/ShopEmailPreviewTask.php
* use templates from defined themes, fixes #793
* add extensions to ShopEmailPreviewTask, fixes #794
* update documentation
> Improve email generation and testing

- .github/workflows/ci.yml
- src/Checkout/Component/AddressBook.php
- src/Checkout/OrderEmailNotifier.php
> CI: omnipay doesn't have a master branch any more

- src/Checkout/OrderEmailNotifier.php
- templates/SilverShop/Model/Order_CancelEmail.ss
> CancelEmail should have its own template.

- src/Page/Product.php
> Use NumericField instead of TextFiled for BasePrice

- lang/da.yml
- lang/de.yml
- lang/en.yml
- lang/fr.yml
- lang/hr.yml
- lang/nb.yml
- lang/nl.yml
- lang/nn.yml
- src/ORM/FieldType/I18nDatetime.php
Update I18nDateTime.php to match the DateTime format syntax
Replace old strftime format with consistent DateTime format
Thank you.
> Update I18nDateTime.php & lang files for DateTime format

- .github/workflows/ci.yml
- composer.json
- lang/en.yml
- src/Forms/AddProductForm.php
- src/Model/Order.php
- tests/php/Admin/ProductBulkLoaderTest.php
- tests/php/Checkout/CheckoutTest.php
- tests/php/Checkout/Component/CheckoutComponentTest.php
- tests/php/Checkout/ShopPaymentTest.php
- tests/php/Extension/SteppedCheckoutExtensionTest.php
- tests/php/Forms/AddProductFormTest.php
- tests/php/Forms/CheckoutFormTest.php
- tests/php/Model/OrderTest.php
- tests/php/Page/AccountPageTest.php
- tests/php/Page/CheckoutPageTest.php
- tests/php/Page/ProductCategoryTest.php
- Provide test for some marked as incomplete
- Update AddProductForm.php.  Set quantity to maximum when over.  Added localisation response to en.yml.
- Update Order.php.  Removed the Director::is_cli check as the issue referenced has been resolved.
- Update composer.json.  Add omnipay/manual as a development requirement for shop payment test.
- Update ci.yml.  Remove items that are not needed.
Thank you.
> Update various tests marked incomplete

- src/Page/Product.php
- src/Page/ProductController.php
move getFormClass() to controller as SS complains:
method 'getFormClass' does not exist on 'SilverShop\Page\ProductController'
also had to rollback the $this->data()->getFormClass() update to be $this->getFormClass()
> Update Product.php & ProductController.php
